# -*- coding: utf-8 -*-
"""Python_09_Excecoes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FoEdXH13lKnGaN8Mx-bfRiF0tPrkNSEd
"""

#TRATANDO EXCEÇÕES

#criando a lista de estudantes

notas = {'João': [8.0, 9.0, 10.0], 'Maria': [9.0, 7.0, 6.0], 'José': [3.4, 7.0, 8.0],'Cláudia': [5.5, 6.6, 8.0],
         'Ana': [6.0, 10.0, 9.5], 'Joaquim': [5.5, 7.5, 9.0], 'Júlia': [6.0, 8.0, 7.0], 'Pedro': [3.0, 4.0, 6.0]}

try:
  nome = input("Digite o nome do(a) estudante: ")
  resultado = notas[nome]

#Forma 1
#except Exception as e:  #tratando a exceção
#  print(type(e), f"Erro: {e}") #imprimindo o erro

except KeyError:
  print("Estudante não matriculado(a) na turma")

else: #será executado se o programa seguir o fluxo do try
  print(resultado)

finally: #será rodado com ou sem exceção
  print("A consulta foi encerrada!")

#CRIANDO A PRÓPRIA EXCEÇÃO

#criando a função
def media(lista: list=[0]) -> float:
  '''Função para calcular a média de notas passadas por uma lista

  lista: list, default[0]
    Lista com as notas para calcular a média
    return calculo: float
    Média calculada
  '''

  calculo = sum(lista) / len(lista)

  if len(lista) > 4:
    raise ValueError("A lista não pode possuir mais de 4 notas")

  return calculo

#tratando os erros

try:
  notas = [6, 7, 8, 8]
  resultado = media(notas) #passando as notas para o cálculo de médias
except TypeError:
  print("Não foi possível calcular a média do(a) estudante. Só são aceitos valores numéricos!")
except ValueError as e:
  print(e) #imprime o erro contido no raise
else:
  print(resultado)
finally:
  print("A consulta foi encerrada!")